/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.views;

import beans.Customer;
import client.Client;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mouna
 */
public class FormListClients extends javax.swing.JInternalFrame {

    private Client client;
    private DefaultTableModel tableModel;

    FormListClients(Client client) {

        this.client = client;
        this.client.askForClients();
        while (this.client.getCustomers() == null) {
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(FormListClients.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        String[] entetes = {"Prénom", "Nom", "Sexe", "Date naissance", "Adresse", "Code postale", "Salaire"};
        Object[][] donnees = new Object[this.client.getCustomers().length][7];

        for (int i = 0; i < this.client.getCustomers().length; i++) {
            donnees[i][0] = this.client.getCustomers()[i].getPrenom();
            donnees[i][1] = this.client.getCustomers()[i].getNom();
            donnees[i][2] = this.client.getCustomers()[i].getSexe();
            donnees[i][3] = this.client.getCustomers()[i].getDateNaissance();
            donnees[i][4] = this.client.getCustomers()[i].getAdresse();
            donnees[i][5] = this.client.getCustomers()[i].getCodePostale();
            donnees[i][6] = this.client.getCustomers()[i].getSalaire();
        }

        tableModel = new DefaultTableModel(donnees, entetes);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jTable1.setModel(this.tableModel);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Formulaire ISF 2017");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int rowIndex = 0, colIndex = 0;
        rowIndex = this.jTable1.getSelectedRow();
        colIndex = this.jTable1.getSelectedColumn();
        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(this, "You have select one row before click on the button");
        }else{
            Formulaire_ISF1 formulaire_ISF1 = FormSingleton.getListISF1Form(client);
            formulaire_ISF1.setVisible(true);
            this.client.getForm().getDesktopPane().add(formulaire_ISF1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
